[versions]
kotlin = "2.0.0"

android-build-tools = "35.0.0"
android-gradle-plugin = "8.9.0"

androidx = "1.0.0"
jackson = "2.8.6"
jpa = "3.0.0"
reactor = "3.2.2.RELEASE"

rxjava2 = "2.2.3"
rxjava3 = "3.1.8"
kotlinx-coroutines = "1.8.0"
ksp = "2.0.0-1.0.19"